### ISSUE TITLE
Allow re-entrant code within same Thread?

### ISSUE THREAD

**Issue by molexx** [alturkovic/distributed-lock#17]
Currently a single Thread of execution cannot call the same `@Locked` method twice (or more) with the same parameter values. I think maybe this should be allowed as the Thread already 'owns' the first lock? Java's `synchronized` allows this.

It's happening to us where we override a `@Locked` method in a subclass and call `super.method()`, and it looks like distributed-lock's advice is run twice - first for the subclass's method call and then again when it calls its parent class's method with `super.method()`.

**Comment by alturkovic** [comment]
Interesting, looking into it today, might take a few days to think about it, busy week :)

**Comment by alturkovic** [comment]
This has proven quite tricky TBH, so sorry for the late reply. I am not sure if it is right to "ignore" locks of overriden methods. Also, what should happen if they are different locks? One could be a Redis lock, the other a JDBC lock. What if they try to lock a different key or even worse, one locks a single key, the other multiple keys? 

I think there are too many ifs in my head currently to do this properly. Any suggestions are welcome...

**Comment by molexx** [comment]
It's not really "ignoring" a lock if the current flow of code (assume Thread for now) already holds that lock. A Thread can't run concurrently! I don't think method overriding in particular needs special handling, it's just one example of where the same flow of code could legitimately try and grab the same lock twice.

It would have to be the same type of lock and each key should be treated individually. If method 1 uses a multi redis lock to grab multiple keys A, B and C then calls method 2 which uses a single redis lock to lock just key A, it should be allowed because that Thread already holds a redis lock on key A.

Yeah I agree it's tricky. When a lock is obtained store an allocation of each key to the Thread that acquired it. When a lock is requested, skip the keys that are already allocated to this Thread. Perhaps ThreadLocal would be useful?

Might need to store a count of aquriations and releases for each key so that the lock is only actually released (from distributed store) when the count gets back to 0. Also useful for sanity checking and debugging purposes to find things that have forgotten to release.

Also need to clear those allocations on expiry, I haven't seen a hook for that?

**Comment by alturkovic** [comment]
That is quite a different idea than what I had in mind initially :D 

I see your point and I think it is valid. I would like to keep the default behaviour but allow a new flag on each annotation to mark it as valid for re-entrant behaviour.

This will probably take quite a while to implement since I don't have a lot of spare time at this point...

> Also need to clear those allocations on expiry, I haven't seen a hook for that?

Could you elaborate what you are missing? Each lock is cleared in the distributed store already using the `Lock.release(List<String> keys, String storeId, String token)` method. The locks themselves have TTL if possible to have them auto-expire in case the application ends unexpectedly. In cases where we do not have TTL, such as SQL, the expired locks are deleted before acquiring them.

**Comment by molexx** [comment]
> I would like to keep the default behaviour but allow a new flag on each annotation to mark it as valid for re-entrant behaviour.

Yes makes sense.


> > Also need to clear those allocations on expiry, I haven't seen a hook for that?

> Could you elaborate what you are missing? 
The locks themselves have TTL if possible to have them auto-expire in case the application ends unexpectedly. 


When the TTL is reached the Thread/key allocation needs to be cleared. 

> In cases where we do not have TTL, such as SQL, the expired locks are deleted before acquiring them.

Ah ok, the Thread/key allocation should be cleared at that point, and a similar place would need to be added for for the stores with TTL e.g. Redis.

**Comment by molexx** [comment]
I've been having a go at this, it is indeed tricky.

Overview:
- on successful `acquire()`, the keys and token are stored in a 'I already acquired this key and here's the proof' Map in the Thread's ThreadLocal.
- when `acquire()` is called again before `release()`, a per-key count is incremented but the store record is not changed
- on `release()` each key's count is decremented and removed from that Map when the count reaches 0
- each store's implementation's `acquire()` query needs to be enhanced to take a token per key and return `true` if there is already a record for the key but it has the given token


TTL is the biggest complication. The only way I can see to handle it requires changing the code for each store type to do a check to see if any of the previously acquired locks are still held with the same token.

My WIP is in a branch here: https://github.com/molexx/distributed-lock/tree/feature/reentrant , the main change is in this commit:  https://github.com/molexx/distributed-lock/commit/50e2eac28a91b100b3ca6c23ccdfd4c9414590c8

So far I have implemented SimpleRedis fully, and MultiRedis partially: TTL is not handled yet. The others have been changed only to compile and pass existing tests.

Re-entrant specific tests to be written.

Where would be best to put the re-entrant enable/disable flag? As an additional parameter on every `acquire()` method?

**Comment by hanserya** [comment]
It seems like this can happen transparently and without external API changes, but people would need to plan to change their table schema if they are employing jdbc locks.

If you want you make the locks re-entrant, then it seems like using a thread-local static variable to store a correlation key for the thread would be sufficient to implement to the requisite logic.

I think the check within each store could simply "allow" the lock to be taken again if the current lock for the key contains the same correlation key as the running thread. You could even add a bonus and extend the lock expiration in accordance with the meta data provided on the current lock request. I'd also add an `acquires` (naming?) field to the lock that is incremented when it is taken again by the same thread and then decremented each time it is released. The final release would delete the lock.

To make re-entry optional, you would just replace the static field with a provider object. If re-entry is enabled, then the provider spits out the value from a thread safe correlation key. Otherwise, it could just spit out a new key each time and cause the framework to operate as it does now.

The refresh logic would be a little interesting when crossing boundaries like that and I am not sure that I have a clean answer for you. It seems like we would need to revert back to a prior cadence after each release of the lock that does not bring the `acquires` field to 0, but I am not sure how involved that would be given the current implementation details. 

I would shy away from making re-entry a non-default behavior but that is just a style preference. I've found little use for non-reentrant locks in my career personally but mileage obviously varies in this job. If re-entry does end up being optional by default, then would it be possible to set a property in on the classpath that make the framework reentrant by default? If the entry behavior was an enum instead of a boolean, then this would be that much easier to accomplish.

**Comment by alturkovic** [comment]
@molexx @hanserya, thank you both for your great help! I have an idea how to do this properly, but unfortunately, I just can't find the time. I am currently switching jobs so that is taking up most of my free time. As soon as I land a new job, I'll tackle this.

**Comment by alturkovic** [comment]
Sorry for the late response, I have looked into this and I don't think I will add support for this. It adds more complexity than I am comfortable maintaining. 

For such needs, I would recommend you take a look at `Redlock` algorithm or some more advanced algorithms. Best of luck!
