### ISSUE TITLE
What is the reason behind only using JitPack?

### ISSUE THREAD

**Issue by mityakoval** [alturkovic/distributed-lock#45]
I was about to start using this library for a project at the company I work for. But the first link on Google points to [an issue in the Gradle repo](https://github.com/gradle/gradle/issues/16310) where it is argued against using JitPack due to multiple security concerns. This is a show stopper for my company at least. And I imagine for many others as well. I can see that previous version were published on Maven Central. So the question is why stop using it?

**Comment by alturkovic** [comment]
I never published them on Maven Central, I have no idea how those ended up there...
I decided to use JitPack because it was simpler for me, I did not have to setup anything and it worked out of the box and I have been using it for years without any problems.

Feel free to open a PR with the Maven publishing plugin and instructions on how to set it up and use it, I will gladly accept it.
