### ISSUE TITLE
Is there a way to try to acquire a lock only once?

### ISSUE THREAD

**Issue by AndreaAdvanon** [alturkovic/distributed-lock#6]
I'd like to be able to try to execute a method, but if the lock can't be acquired it should simply fail and never retry. Is it possible out of the box?

**Comment by alturkovic** [comment]
There is manual acquire, take a look at [this](https://github.com/alturkovic/distributed-lock#manually-controlled-locks). This way you have complete control over the locks.

But I think setting the `@Locked(timeout = @Interval("0"))` should also work. If not, I'll definitely add a way to bypass the retry mechanism through the annotation.

Please let me know if you manage to do it :)

P.S. Did you close because you managed to do it yourself?

**Comment by AndreaAdvanon** [comment]
I closed it because this was not actually the problem :smile: 
I notice that the annotation to work bust be placed in a method that is called from another class, not the current one.
Like:


```kotlin
@Service
class MyService {
   
   fun doSomeThing() = doThing() // Not working here   

   @JdbcLocked
   fun doThing() = "thing"
}

@Service
class MyOtherService(private val myService: MyService) {
    fun doSomeThing() = myService.doThing() // Works here
}
```

Is there a way around it besides using the manual lock?

**Comment by alturkovic** [comment]
Well that is the way proxies and local method calls work. When your method calls a local method, you bypass the proxy and thus the annotation is useless. I'm sure there are way better explanations available online. Glad to hear you solved the issue :)

**Comment by alturkovic** [comment]
I was actually trying to explain self-invocation, take a look at the official doc here: https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#aop-understanding-aop-proxies (sorry about formatting, I'm on mobile)

**Comment by AndreaAdvanon** [comment]
Yes this is what I thought, thanks!
